### ISSUE TITLE
Support For External Apps

### ISSUE THREAD

**Issue by XHYN-PH** [FWGS/xash3d-fwgs#1002]
Hi... can developers add support for external apps like CS16Client or BSLauncher etc..
Because when i try it the Old engine its running not this new engine is there a way to run it with other external apps? Like same package name? Identical to Old Engine?

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/90

**Comment by nekonomicon** [comment]
Nope.
Need to recompile all apps for new engine because:
1. new engine has 64-bit libraries, and an old apps not.
2. new ndk does not support hardfp.
3. we have new intent.
4. we had plans to exclude java code from apps.
5. arm vendors had plans to drop 32-bit code support from new 64-bit chips in 2022.

Also, you can run Blue Shift using command line args`-game bshift`.

**Comment by XHYN-PH** [comment]
Thanks for replying guys i will try this... by the way theres a annoying bug when Half-Life is at Loading proceed in-games the screen is glitch then it will back..
