### ISSUE TITLE
Transparency problems

### ISSUE THREAD

**Issue by tyabus** [FWGS/xash3d-fwgs#101]
Sometimes on some view angles transparent things stop being transparent.

**Comment by revelator** [comment]
heh i wonder if this is what has been bugging me on my end though i get the reverse with vbo on (things that should be opaque turn transparent at some angles). I had this i remember with an old quake engine project i worked on, turned out to be that culling went beserk when i ported the old immediate mode renderer to vertex arrays. Took me a while to iron out also.

**Comment by Vladislav4KZ** [comment]
https://www.youtube.com/watch?v=aoQNGEeW6Kg

**Comment by nekonomicon** [comment]
If it's VBO trouble, may be closed?

**Comment by a1batross** [comment]
Should be fine with vbo-fix merge. Reopen if it's still broken.
