### ISSUE TITLE
black screen on opposing force

### ISSUE THREAD

**Issue by revelator** [FWGS/xash3d-fwgs#103]
the cutscenes render ok but the start map at the scientist trying to save your life, is rendering all black making it impossible to see anything. 

Tries with vbo on or off it makes no difference.

gfx card is an R9 390 AMD

**Comment by EternalCringe** [comment]
Wrong cahce, maybe?

**Comment by revelator** [comment]
Not sure what cache you mean ?, i noticed though that normal rendering will resume if you wait a few minutes (way past when it should have) so something is definatly up. 

VBO's still not working on AMD also, i get world bleed through
when using flashlight and in opposing force when using the portal gun.

**Comment by nekonomicon** [comment]
New engine has bug with fade.

**Comment by revelator** [comment]
Ouch :S, thats a pretty nasty bug hope it is fixable.

Im wondering if porting idtech4 VBO code would work on xash as it works fine on my card.
The idtech vbo code initialises with stream draw before static draw but im not sure this is what causes the world bleed through. 

I have noticed that the vbo code in both engines are pretty prone to error if something is done incorrectly especially on AMD cards.

**Comment by nekonomicon** [comment]
Create another issue for VBO then.
One issue per bug.

**Comment by revelator** [comment]
will do.

**Comment by sixcentgeorge** [comment]
the bug is present in latest 2.0 release but not previous 0.9 that is at moddb.
i play using hl won 1110 and gearbox . both from clean recent install .
the bug appears to me in different maps of different mods..
it is linked to the the cvar of @SolidClass = worldspawn : "World entity" : 
  startdark(choices) : "Level Fade In" : 0 =
  [ 
    0 : "No"
    1 : "Yes"
  ]

it does not appear in the first map of blu shift : ba_tram1 [ may be because player is in a moving train ] but in others maps or if you add it in a compiled map .

**Comment by SaikoHaven** [comment]
It seems as of now, a workaround is to load opfor with console, and run `v_dark 0` at the proper time in of1a1

**Comment by sixcentgeorge** [comment]
i think that bug is more or less related to this map..
the famous uncle mike... does not "appreciate" those who find bugs or give ideas "at their right valors" ... so he is only have few friends from "sovietscccp" team .. [ the mod only played by " devs , admins, moderators & full members [those who gave money and those who will.. ] beware in his forum : he does like solo-sniper-killer-viking at sovietscccp : he kills in the back without warning... for , mainly , stealing purposes ...lol ] "

**Comment by a1batross** [comment]
@sixcentgeorge last warning, do not spread nonsense or you'll banned from FWGS issue tracker.

**Comment by sixcentgeorge** [comment]
hit me please ..hit me with your ban's hammer ... i am one of the few target you are only able to not miss.. it s not the same with bugs.. or truth.. ban truth is something you did long ago.. that is sad : i enjoy "reporting or discussing bugs with you.. being more blind than stevie wonder" : i do not care what you think .. i had fun showing to all that : i find bugs and more..and i am not the mothofockor some shithole try to make ...of my reputation.. i think i clearly inversed the TREND of the "who 's who : motherfucker" and now like many others : you are on the other side of guns.. something that will happen soon in Husrahell  $$ too

**Comment by SaikoHaven** [comment]
Become fluent before trying to type english. I don't understand a WORD you
said.

**Comment by lewa-j** [comment]
Retest please

**Comment by revelator** [comment]
Ok been away a while but managed to test it again and vbo is still a nogo with my AMD card unfortunatly. This time however it seems to have yielded some clue as to what might be going wrong  as it threw an invalid opengl call when it happend. Sadly the game crashed so i was not able to see where in the code it happened, i hope to trigger it again but is there a way to log such things to a txt file built into the engine ?.

**Comment by nekonomicon** [comment]
I think must be closed already.
