### ISSUE TITLE
multiple monitors cause issues

### ISSUE THREAD

**Issue by Jan200101** [FWGS/xash3d-fwgs#111]
When testing the master branch I found the game stuck on my left monitor using the resolution of my main monitor
I haven't found anything in the settings to fix this or an existing issue talking about this

[log](https://gist.github.com/Jan200101/cc9d2e8079afd773645ad908f706f6d2)

**Comment by a1batross** [comment]
It could've been the SDL2 bug because it doesn't happen anymore on my multi-monitor setup.

Of course, we still query only one monitor screen resolution, this is unfortunate, and always apply all settings to the 0-th monitor from SDL2 point, I haven't really found a way to force SDL2 move window to another screen and apply full-screen there.
