### ISSUE TITLE
"Fire the rocket engine..." NPC's mouth doesn't move

### ISSUE THREAD

**Issue by OpenRift412** [FWGS/xash3d-fwgs#1223]
Don't know why this is the case.

**Comment by a1batross** [comment]
Can you describe this in detail?

**Comment by OpenRift412** [comment]
> Can you describe this in detail?

When you approach this NPC in Blast Pit and he begins his dialogue, his mouth doesn't move when he speaks. He goes through his other animations, but not for his mouth.

**Comment by a1batross** [comment]
Thanks for bug, turns out such sounds wasn't handled correctly. Some sounds in GoldSrc are meant to never be overriden, in this case it's a game NPC telling the player valuable information, while other sound channels are used by tentacles. This was never a problem for us, as we have more channels than GoldSrc.

Anyway, fixed in https://github.com/FWGS/xash3d-fwgs/commit/6df25392b8bccc684702e801f5722b0a2887a8fd and https://github.com/FWGS/xash3d-fwgs/commit/279e3919490787eeb493653ca7cd8a3810a2b5de
