### ISSUE TITLE
Entities play their previous animation frame (??) after reloading save

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d-fwgs#1302]
Which shouldn't happen, after loading save we should be at exact same animation frame.

Doesn't happen in normal Half-Life, as it doesn't save schedule data. Requires this patch: https://gitlab.com/vasiavasiavasia95/guard-duty-xash/-/commit/f5b2a1c33f4cbefb54abe87d6fa927ac9c3350ff

Demo: https://cdn.discordapp.com/attachments/1047088991301804064/1087363977501216861/2023-03-20_20-10-31.mp4

**Comment by vasiavasiavasia95** [comment]
As the person who found this horrible evil thing I wanted to provide more info on what the hell this is. 
It seems to me that somehow cl_entity_t's state carries over from the current game resulting in the studio model interpolation code freaking out and interpolating the transion from the last animation frame model was in before the saveload and the new animation frame restored from the save file. Brush based entities are working with no issues,

Normally this isn't noticable at all as HL1 AI resets animations and this interpolation bug only happens if the model was in the same animation before and after the saveload.

This problem doesn't occur in steam Goldsrc at all where I originally made and tested my patch on.

**Comment by a1batross** [comment]
So the root cause is that `g_studio.time` doesn't get updated on CL_GetStudioEstimateFrame call, which is called before rendering to setup `latched.prevframe` field in cl_entity_t. 

First possible fix is to call R_StudioSetupTimings in R_StudioEstimateFrame, so `g_studio.time` 

Also, @vasiavasiavasia95 has found another edge case, where bug still occurs if savefile was loaded from menu. Turns out `RI.drawWorld` is still false in `R_StudioSetupTimings` because we aren't actually rendering anything yet and current viewpass is meant for menu rendering.

**Comment by a1batross** [comment]
Fixed with RefAPI 4.

`R_StudioEstimateFrame` function now accepts a time argument by which we can manipulate the target frame.
