### ISSUE TITLE
Feat.req. Enable Discussions tab on Github

### ISSUE THREAD

**Issue by necros2k7** [FWGS/xash3d-fwgs#1351]
subj

**Comment by a1batross** [comment]
I don't want to stick projects that I maintain to GitHub more than it is now, since GitHub is a hostile platform for open-source development.

For example, code published on GitHub is being used in AI model training, without author's consent. To me, it clearly violation of a GNU GPL, which requires all derived source code to be published under GPL as well.

Also, GitHub UI is almost nearly unusable, from technical issues on Firefox where downloads panel just disappears, to UX issues where you can't find "Sign In" button because GitHub care about existing users.
