### ISSUE TITLE
Need help building a launcher for mods,android.

### ISSUE THREAD

**Issue by AmpedgamR** [FWGS/xash3d-fwgs#140]
Hi I'm new to the xash3d thing, is there a way to build an independent launcher for a mod not supported. Is it a thing?

**Comment by nekonomicon** [comment]
Mod porting guide:
https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/mod-porting-guide.md

Launcher example:
https://github.com/FWGS/mod-sample

Our HLSDK fork:
https://github.com/FWGS/hlsdk-xash3d

To build android launcher you need at least:
JDK
Python
Android SDK
Android NDK

For old engine you need to use ant and android NDK r10e.

New engine is not stable yet and we had plans to migrate to waf and the latest NDK version.

Also, you can see .travis.yml and build.sh if you need more information about building process:
https://github.com/FWGS/xash3d-fwgs/blob/master/.travis.yml
https://github.com/nekonomicon/Poke646-android/blob/master/.travis.yml
https://github.com/FWGS/mod-sample/blob/master/build.sh

**Comment by AmpedgamR** [comment]
Thank you.

**Comment by AmpedgamR** [comment]
Hi it's me again, I'm almost done with the mod but what does this error
mean?

App_modules is probably incorrect,
No modules to build.

Again I'm new to coding, but I'm almost done though.

**Comment by nekonomicon** [comment]
Do you read HOWTO.txt?
https://github.com/FWGS/mod-sample/blob/master/HOWTO.txt

**Comment by AmpedgamR** [comment]
Oh crap Sorry I didn't see that sorry for wasting your time.

**Comment by AmpedgamR** [comment]
Never mind it's still giving me the same error. Could you see mine to see
if it's correct?

**Comment by AmpedgamR** [comment]
Ok I fixed the problem, how do you set up the custom mod dll files.

**Comment by abbes255** [comment]
How to complie file half life sdk xash 3d for android with linux terminal plz?

**Comment by nekonomicon** [comment]
Read my comments.

**Comment by abbes255** [comment]
But is not working

**Comment by abbes255** [comment]
![Uploading IMG_20210224_095717.jpg…]()

**Comment by nekonomicon** [comment]
It's working.

**Comment by abbes255** [comment]
How ?

**Comment by abbes255** [comment]
What's the steps for following

**Comment by nekonomicon** [comment]
I already said.

**Comment by abbes255** [comment]
But the terminal say 
./build.sh: 4: ndk_build: not found
./build.sh: 5:ant: not found

**Comment by lewa-j** [comment]
nekonomicon said:
> To build android launcher you need at least:
> JDK
> Python
> Android SDK
> Android NDK

**Comment by abbes255** [comment]
I download it

**Comment by lewa-j** [comment]
You have to learn how to use them.

**Comment by abbes255** [comment]
Ok how to complie to android ?

**Comment by lewa-j** [comment]
That's not specific to xash question. Use google

**Comment by M4RC0-NTH** [comment]
hi..can you help me in this work. i tried to run compile.sh and it output like this:

/data/data/com.termux/files/home                                              -- Configuring for termux
python: can't open file 'xash3d-fwgs/scripts/makepak.py': [Errno 2] No such file or directory
package su.xash.engine;
public class XashConfig {
public static final boolean PKG_TEST = false;
public static final boolean CHECK_SIGNATURES = false;                         public static final boolean RELEASE = false;
public static final boolean GP_VERSION = false;                               }
<?xml version="1.0" encoding="utf-8"?>                                        <resources>
<string name="git_revisions"><b>Version information:</b>\n@localhost 18:37:01-31-01-23</string>
</resources>
Setting top to                           : /data/data/com.termux/files/home/xash3d-android-project
Setting out to                           : /data/data/com.termux/files/home/xash3d-android-project/build
Build type                               : debug
--> android                              : in progress                        Checking for program 'javac'             : ecj
Checking for program 'java'              : true
Checking for program 'jar'               : true
Checking for program 'javadoc'           : true
Checking for program 'zipalign'          : /data/data/com.termux/files/usr/bin/zipalign
Checking for program 'apksigner'         : /data/data/com.termux/files/usr/bin/apksigner
Checking for program 'zip'               : /data/data/com.termux/files/usr/bin/zip
Checking for program 'aapt'              : /data/data/com.termux/files/usr/bin/aapt
Checking for program 'd8'                : not found
Checking for program 'dx'                : /data/data/com.termux/files/usr/bin/dx
<-- android                              : done
'configure' finished successfully (0.185s)
compile.sh: 75: compile.sh: ./waf: not found
cat: /data/data/com.termux/files/home/xash3d-android-project/build-xash3d-fwgs/armeabi-v7a/config.log: No such file or directory


sorry because i am just starting with shell language and cmd from any linux terminal..but my understanding of c,c++ is enough for me..but i need some help when doing this in termux..btw i am running this on Android 5, because I read and saw that this compiler still depends on android 5. so can you help me? maybe just a little instruction is enough to give me a clear understanding.

**Comment by nekonomicon** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/1112

**Comment by M4RC0-NTH** [comment]
and what does that mean...is it possible that this compiler is outdated and doesn't work anymore?

**Comment by nekonomicon** [comment]
Android build currently broken.
Wait when @Velaron's changes will be merged.

**Comment by a1batross** [comment]
Forget about building Xash for Android from source.

Old Android port is dropped. It's not supported anymore.

**Comment by Neurtrino-4321** [comment]
hey can you teach me how to make launcher xash3d fwgs old engine in AndroidIDE
