### ISSUE TITLE
Counter Strike support ?

### ISSUE THREAD

**Issue by TheBrainScrambler** [FWGS/xash3d-fwgs#1408]
Is it possible to run Counter Strike from Xash3D ? And more specifically on Xash3D 64 bits ?

It's listed in https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/not-supported-mod-list-and-reasons-why.md but that list seems deprecated because https://github.com/FWGS/xash3d/tree/vinterface points to the old repo and Blue Shift is supported with its version of the hlsdk at https://github.com/FWGS/hlsdk-portable/tree/bshift.
At https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/supported-mod-list.md it says on PC you can only run the server. But again, is this deprecated ? The link at https://github.com/FWGS/cs16-client is dead. It also says there is Android support with https://play.google.com/store/apps/details?id=in.celest.xash3d.cs16client, so what about PC ?
https://github.com/FWGS/hlsdk-portable/wiki/Mods doesn't list it though.

I'm also aware there is FreeCS (https://github.com/eukara/freecs) but I want to know if Xash3D supports it.

**Comment by a1batross** [comment]
It's not that easy.

1. FreeCS is meant to work under FTEQW. I don't see any reason to make double work to emulate FTEQW extensions of Quake 1 virtual machine, where you could just use FTEQW engine and run FreeCS with it.

2. You technically can run reverse-engineered versions of Counter-Strike. Mainly, for server code usually https://github.com/s1lentq/ReGameDLL_CS is used and for client you could use @Velaron's builds. He publishes them at https://github.com/Velaron/cs16-client/releases/tag/continuous. It should be noted that cs16-client isn't open source anymore, and it's up to Velaron whether he wishes it to be open source or not.

PC isn't listed anywhere because almost every Counter-Strike player uses a mobile phone. And joining matches from PC is just not fair.

3. Original Counter-Strike by default could not be run on Xash3D due to missing VGUI2 support. There is some work done to support VGUI2 on this engine branch, but it's highly WIP. Also, there is no 64-bit support for it, due to client was never ported by Valve to 64-bits and their server port is outdated and won't run on modern systems (mostly due to ASLR now being used everywhere).

**Comment by xLeviNx** [comment]
> It's not that easy.
> 
> 1. FreeCS is meant to work under FTEQW. I don't see any reason to make double work to emulate FTEQW extensions of Quake 1 virtual machine, where you could just use FTEQW engine and run FreeCS with it.
> 2. You technically can run reverse-engineered versions of Counter-Strike. Mainly, for server code usually https://github.com/s1lentq/ReGameDLL_CS is used and for client you could use @Velaron's builds. He publishes them at https://github.com/Velaron/cs16-client/releases/tag/continuous. It should be noted that cs16-client isn't open source anymore, and it's up to Velaron whether he wishes it to be open source or not.
> 
> PC isn't listed anywhere because almost every Counter-Strike player uses a mobile phone. And joining matches from PC is just not fair.
> 
> 3. Original Counter-Strike by default could not be run on Xash3D due to missing VGUI2 support. There is some work done to support VGUI2 on this engine branch, but it's highly WIP. Also, there is no 64-bit support for it, due to client was never ported by Valve to 64-bits and their server port is outdated and won't run on modern systems (mostly due to ASLR now being used everywhere).

My only reply to this would be the same that most communities are already doing. Disabling mouse usage on the server. Other than competitive and pubs, there are many other mods that this could benefit from and expand player base if xash support was extended to PC.

**Comment by a1batross** [comment]
@xLeviNx mouse disabling from server is just a check for an idiot, it's too easy to fake it. Even without recompiling the engine, just by executing a command in GDB.

And CS mods are usually hacky, they might not work with Xash due to it not being compatible with GoldSrc internally at all. As for developing your own mods, I think, ReGameDLL_CS and older open source version of cs16-client should be enough.

**Comment by xLeviNx** [comment]
> 

Ah I see. Thanks for the update nonetheless

**Comment by spraytheunbeaten** [comment]
i shitted my pants btw
