### ISSUE TITLE
Regression: 962f88d breaks flashlight tracing

### ISSUE THREAD

**Issue by TacoDeBoss** [FWGS/xash3d-fwgs#1526]
Hello - commit 962f88d appears to have broken flashlight tracing. I've tested with HL1 and Blue Shift. When multiple enemies are in a scene the flashlight can (and very often will) lock onto the wrong one, displayed in the video below. 

https://github.com/FWGS/xash3d-fwgs/assets/2870898/50f2bf7d-21ec-4bdc-ab84-7fc70c42edc9

This will affect gameplay, often leaving you completely blind in vents for example, as the flashlight locks onto a headcrab 10 meters behind you that you killed a few seconds ago. Reverting 962f88d fixes the issue and the flashlight behaves as expected, displayed below.

https://github.com/FWGS/xash3d-fwgs/assets/2870898/35c7f933-3d68-475a-81d0-52eb695d1640

[engine.log from affected build](https://github.com/FWGS/xash3d-fwgs/files/13622327/engine.log)

### extra notes
You will see the log is from a FreeBSD engine build with clang, but I have also tested and verified this issue to be present on Linux builds with gcc.

**Comment by a1batross** [comment]
The fix wasn't complete. I switched from tracing visible entities to tracing physic entities here to match GoldSrc behavior but I forgot to change the array used to check whether flashlight should attach to an entity.

Should be fixed since: https://github.com/FWGS/xash3d-fwgs/commit/20ced857b42ff568571283f5756205cc800e54c5
