### ISSUE TITLE
[Feature Request] A Viewmodel FOV Setting

### ISSUE THREAD

**Issue by juuuulian-s** [FWGS/xash3d-fwgs#1600]
A command that handles viewmodel FOV independently from screen FOV, allowing for high screen FOV with minimal viewmodel clipping.

**Comment by nekonomicon** [comment]
I'm not sure what you need.
Engine has `r_adjust_fov` cvar for HD screens already.

**Comment by Velaron** [comment]
This is not possible as the weapon is rendered as a part of the world

**Comment by juuuulian-s** [comment]
What about adjusting the near clipping plane? This way theres no need to mess with FOV settings, as the clipping is the main reason I made this request in the first place.

**Comment by a1batross** [comment]
@juuuulian-s can you provide an example where current near clipping value isn't enough? 

I don't see any reason to go lower than 4 units, as it's the default value used in Quake and GoldSource.

**Comment by a1batross** [comment]
I also only notice near clipping when the FOV values go higher than 130 which is already unplayable by itself as it breaks default view models. 

Not sure about drawing viewmodel with separate FOV. Mods with custom renderers can implement it the way they want. If some Xash3D-based game that relies on standard renderer wants it, it might get implemented. If not and you need it just for fun, I don't see reason to make standard renderer any more complicated than it already is.

**Comment by a1batross** [comment]
Turns out, it's quite easy to implement, just by changing projection view matrix before drawing viewmodel and restoring it back.

But field of view is controlled by the game code. Games and mods that modify player's field of view were designed in mind that viewmodel fov will be equal to everything else.

I think, this can be implemented as an extension to `ref_params_t` structure, similar to how `fov_x` and `fov_y` are added at the end of struct. If anybody wants this for their mod, they can open a new issue.
