### ISSUE TITLE
Ingame UI should scale with resolution.

### ISSUE THREAD

**Issue by SheridanR** [FWGS/xash3d-fwgs#1624]
I apologize if this is outside the scope of Xash and is intrinsic to the HL SDK, and I am well aware that the UI not scaling is a historic issue within GoldSrc, but we all know the 25th anniversary release fixed the ui to scale correctly for modern resolutions, and I believe Xash should do the same.

**Comment by a1batross** [comment]
There are three ways to do this:
1. Use HL25's client.dll that has special code to load high resolution sprites.
2. There is pending patch for hlsdk-portable that adds HL25 high resolution sprites https://github.com/FWGS/hlsdk-portable/pull/412
3. Use `hud_scale` engine cvar. It might be slightly buggy because it lies to client.dll about our resolution and then scales sprites up during rendering. It also requires game restart (saving game and reloading is enough)

**Comment by SheridanR** [comment]
That's really helpful info, thank you. I wonder if it would be useful to expose hud_scale in the main menu ui just to increase visibility to the end user?

**Comment by a1batross** [comment]
`hud_scale` is still a hack and without proper support from mod it produces ugly results, like black borders around the scaled sprite.
