### ISSUE TITLE
Crash on updating Con_LoadHistory method

### ISSUE THREAD

**Issue by adslbarxatov** [FWGS/xash3d-fwgs#1671]
Hi!

We've found a breach in new version of `Con_LoadHistory` method. We've attached the `console_history` file created by previous version (March 2024) of the engine. It has some obvious miswritings (multiple `0x0D` characters). Older version of the engine was able to parse this file without crashes. The new version of the engine (May 2024) makes no miswritings and works fine if you clear the console history.

But if we using this file the method causes a memory access violation (with non-sense address) somewhere outside the engine assemblies (we can't precisely locale it using Visual studio and complete PDB's for all DLLs). We only found out that the crash comes from the `FS_Gets` method on the second iteration of the cycle inside the `Con_LoadHistory`. But if you using step-by-step debug mode (F10 / F11), the method finishes without a crash. Like it somehow depends on the speed of the execution.

Hope, our little investigation will help you to workaround this case and create a safe patch. Because we can't understand how to do that for now.

Best regards,
Nicolay B.

![console_history](https://github.com/FWGS/xash3d-fwgs/assets/20893717/c9153a4f-79b8-4119-a1a9-b0e2e09e061a)

[console_history.txt](https://github.com/FWGS/xash3d-fwgs/files/15257926/console_history.txt)

**Comment by a1batross** [comment]
Fixed in 3917c2589d9fd6fffeab3964a14fa3e4f7f94dfb.

Sorry it took me a week, didn't have enough time to work on Xash :)

The bug was caused by the change in https://github.com/FWGS/xash3d-fwgs/commit/081cf9132bd8bc7ad8a81e2af6fccbfe5dd1e3da but thanks to it, we at least don't cause buffer overflow in FS_Read anymore.

The issue with empty lines (caused by repeated carriage return) is a bit more obvious to me now, I will try to fix it too.
