### ISSUE TITLE
Remember Server Settings

### ISSUE THREAD

**Issue by FK2FAGHMS** [FWGS/xash3d-fwgs#1675]
This functionality is not working on 0.20 version, while it works on the older versions such as 0.19.3.
I'd prefer to have this version to play with since it has brightness setting and no "CTRL stops working unless you go back to menu" bug (on VGUI Games).
But having to re-configure everything from scratch every time I start a LAN game is just frustrating.

**Comment by a1batross** [comment]
This is actually a known bug. 

We don't exactly _save_ the data in `.scr` files. In my opinion, we should save SCR files the way GoldSrc does, rather than saving it somewhere else. I also don't think it should be handled in engine, since these were made specifically to be handled by the UI.

There are also some existing bugs with it. I've tried to fix them some time ago but unsuccessfully. :(

**Comment by Vladislav4KZ** [comment]
I have already reported about this: https://github.com/FWGS/xash3d-fwgs/issues/509

Closing as duplicate.

**Comment by FK2FAGHMS** [comment]
The issue is in Russian, how do you expect non-Russian speakers to understand and refrain from opening a new issue? You should either make it in both languages or re-open my issue. 
Or, close them both because I found out this version was released 5 years ago! 5x365 Days! Looks like nobody did bother creating listen server since then! If it hasn't been fixed in 5 years, then I won't be asking for anything, and simply stick to Goldsrc.

**Comment by a1batross** [comment]
Yeah, because some users can't be bothered learning an English, we accept issues in Russian as well. I tried to fight over this and lost.

But I think, with modern machine translation capabilities, especially in tech language, it's quite possible to use both languages. Just write in English or Russian, whatever you know better, and let the machine translation, like DeepL or Google Translate, handle everything else.

> Or, close them both because I found out this version was released 5 years ago! 5x365 Days! Looks like nobody did bother creating listen server since then! If it hasn't been fixed in 5 years, then I won't be asking for anything, and simply stick to Goldsrc.

What exactly doesn't work for you? You can save settings in a config file.

Implementing the correct order to apply UI settings, save them, while also not breaking existing mods, isn't that easy. It was also broken in old engine as well.

**Comment by a1batross** [comment]
Also cut your "hasn't been fixed in 5 years" nonsense.

Xash3D FWGS is made by volunteers, not a company. In the end, we don't owe you anything.
