### ISSUE TITLE
Numeric release tags?

### ISSUE THREAD

**Issue by romulasry** [FWGS/xash3d-fwgs#1695]
For Linux, see: https://release-monitoring.org/project/241708/

**Comment by a1batross** [comment]
That would be awesome, but we don't have stable releases yet.

I really want to finally start making stable releases, but I also don't want to tag stable releases with undone Android support.

By the way, this website is misleading. It shows a bunch of tags, but haven't checked them since 2022. The latest engine is always available at https://github.com/FWGS/xash3d-fwgs/releases/tag/continuous
