### ISSUE TITLE
Quake WAD2 and Alias MDL formats broken 

### ISSUE THREAD

**Issue by laurarvix** [FWGS/xash3d-fwgs#1730]
Last observed a few updates back, but Quake maps with textures compiled into the map would display Half-Life skies and all other textures as pitch black. Additionally, when renaming Quake's "progs" folder to "models," the game will crash on startup with a message mentioning an unsupported model format.

**Comment by a1batross** [comment]
>Quake maps with textures compiled into the map would display Half-Life skies and all other textures as pitch black

Pitch black textures probably were fixed in https://github.com/FWGS/xash3d-fwgs/commit/85dfaaa2c2f8894204b9a6fb4e867dd54dfde219. If it still happens, can you attach a map or send it to me in DM?

>unsupported model format

Fixed, alias models can now be loaded since 0f8f35b415c56af799298ed6ab6e9a2749e2f0cb

While on it, I also fixed a few other Quake Wrapper/Quake Remake bugs, like the screen blend effect when picking up items, incorrect dynamic light on player with `EF_DIMLIGHT` effect and Quake demo compatibility.
