### ISSUE TITLE
[OpenGL] Some decals are rendered with artifacts

### ISSUE THREAD

**Issue by OlegAckbar** [FWGS/xash3d-fwgs#1743]
Here are examples of such decals
My system:
Operating System: Arch Linux 
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.10.2-2-cachyos (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 15.6 ГиБ of RAM
Graphics Processor: AMD Radeon RX 6700 XT

![Снимок экрана_20240728_154220](https://github.com/user-attachments/assets/3c9806e6-abb1-4711-90b0-d755523dd2b5)
![Снимок экрана_20240728_154143](https://github.com/user-attachments/assets/1e522700-7656-495e-a76a-50ab0f2b5795)
![Снимок экрана_20240728_153828](https://github.com/user-attachments/assets/61b7d048-8935-4034-8b48-9d8b1396ae50)
![Снимок экрана_20240728_153811](https://github.com/user-attachments/assets/abc16982-0043-4328-8384-391f6482352a)
![Снимок экрана_20240728_153801](https://github.com/user-attachments/assets/f17cafe1-78cc-402a-8e2b-a838a258979c)

**Comment by a1batross** [comment]
Does `gl_vbo` is enabled?

Which renderer do you use? `r_refdll_loaded` in console.

Also, run engine with `-dev 2 -gldebug -log` arguments and post engine.log here.

**Comment by OlegAckbar** [comment]
@a1batross 

1. `gl_vbo` was not enabled
2. `r_refdll_loaded" is "gl" ( "" )`
3. [engine.log](https://github.com/user-attachments/files/16404559/engine.log)

**Comment by TacoDeBoss** [comment]
Pitching in some info -- I experienced this exact same thing last night and spent a few hours debugging it. This issue manifests after compiling on my Arch Linux machine with gcc 14.x. A bisect was impossible because no matter how far I went back, it was still happening.

![xash-arch](https://github.com/user-attachments/assets/784c1c66-5996-4e6f-a393-78f9e2c310ae)


However, I discovered that the latest master branch compiled in an Ubuntu 20.04 VM with gcc 9.3.0 produces a build without the issue.

![xash-ubuntu](https://github.com/user-attachments/assets/55463f43-bed9-4adf-926e-87d5ce48d502)

The issue is in libref_gl.so specifically - replacing this file with the one built from the Ubuntu VM solves the problem.
It seems very strange to me to be a compiler issue, and I couldn't get the engine running after building with clang to narrow down whether it really is the compiler or some other library. Currently, I can't say much more now than "this happens on Arch but not Ubuntu 20.04."

**Comment by a1batross** [comment]
Thanks for the info!

Welp, I'm still on GCC 13.2. I do have GCC 14.0 installed though, but I never tried to compile the engine with it.

**Comment by mittorn** [comment]
Maybe it's because new gcc prevents writing array out of bounds (which 
is UB, but used somewhere for arrays in end of struct in engine)?

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d-fwgs/blob/master/ref/gl/gl_decals.c#L510
glpoly_t used...

https://github.com/FWGS/xash3d-fwgs/blob/master/common/com_model.h#L130

I think, we may add some macro for glpoly verts access that does not 
refers it as glpoly_t

Of course 0-3 verts are drawn correctly, but 4th breaks and goes to zero 
(in the sky on crossfire, as seen on screen)

**Comment by a1batross** [comment]
> Maybe it's because new gcc prevents writing array out of bounds (which is UB, but used somewhere for arrays in end of struct in engine)?

This is a feature in C

**Comment by mittorn** [comment]
flexible struct array member (without specified size) is feature. Array 
with fixed size is not flexible.  glpoly_t is not flexible. We cannot 
fix this structure without breaking compatibility, but can change it's 
usage in engine.

**Comment by a1batross** [comment]
We just have to allocate the same amount of space to keep it's compatible.

Did you check that changing the glpoly_t definition helps to avoid this issue?

**Comment by mittorn** [comment]
How i supposed to change it to fix it? I cannot change it to flexible 
array member because it will change stucture size and break existing 
code.
Instead, we need add new structure with different name and cast glpoly 
pointer to it instead

**Comment by a1batross** [comment]
Fixed.
