### ISSUE TITLE
[Question]How to make custom font using .fnt format

### ISSUE THREAD

**Issue by Vad1mCSO2** [FWGS/xash3d-fwgs#1804]
[fnt fonts.zip](https://github.com/user-attachments/files/16747271/fnt.fonts.zip)

**Comment by a1batross** [comment]
`makefont` tool from HLSDK

**Comment by Vad1mCSO2** [comment]
It makes only wad format not fnt

**Comment by Vad1mCSO2** [comment]
![image](https://github.com/user-attachments/assets/03670a48-e2ce-493a-a766-50467d4495b6)
there are only bitmaps

**Comment by Vad1mCSO2** [comment]
[BKTCP1251.zip](https://github.com/user-attachments/files/16748550/BKTCP1251.zip)
I trying to generate to .fnt with CP1251 encoding

**Comment by Vladislav4KZ** [comment]
@Vad1mCSO2 you don't need .fnt format to support cp1251. Custom makefont can create fonts.wad with Cyrillic support.

**Comment by Vladislav4KZ** [comment]
It's in hlsdk-portable repository:
https://github.com/FWGS/hlsdk-portable/tree/master/utils/makefont (you need to compile the exe yourself).

**Comment by Vad1mCSO2** [comment]
> @Vad1mCSO2 you don't need .fnt format to support cp1251. Custom makefont can create fonts.wad with Cyrillic support.

Fonts.wad applies only console. I need only credits font

**Comment by Vladislav4KZ** [comment]
> > @Vad1mCSO2 you don't need .fnt format to support cp1251. Custom makefont can create fonts.wad with Cyrillic support.
> 
> Fonts.wad applies only console. I need only credits font

Creditsfont is located in gfx.wad. You need to use Wavelength Gfx.wad compiler to create gfx.wad.

But by default it does not support Cyrillic. You may have to edit creditsfont.txt adding Cyrillic letter coordinates there.

**Comment by Vladislav4KZ** [comment]
https://github.com/Fograin/hl-subs-mod/tree/master/dev_tools/make_gfx

**Comment by Vladislav4KZ** [comment]
Anyway, Wavelength Gfx.wad Compiler can not convert ttf font to bmp. You need exactly the bmp image with font.

**Comment by Vad1mCSO2** [comment]
![image](https://github.com/user-attachments/assets/b7f434e3-dda7-469a-8573-c2d29ce0eaef)
![image](https://github.com/user-attachments/assets/6c291fc5-32b6-4729-9873-4322e6e5b926)


> Anyway, Wavelength Gfx.wad Compiler can not convert ttf font to bmp. You need exactly the bmp image with font.

**Comment by mittorn** [comment]
Use any utilty that makes fonts.wad (IIRC i used UnkleMike's patched 
makefont)

Then, use HLLib/gcfscape to unpack fnt lumps from wad

Engine font renderer is extended to look for fnt files instead of 
specific wads (not any wad)

This is made to support cp1251/cp1252 fonts with original game files 
with ability to set codepage from console (con_charset sets target font 
codepage, cl_charset sets client strings codepage. con_charset 1252 + 
cl_charset utf-8 turns on utf-8 to cp1252 conversion, but setting both 
to cp1252 makes whole client run in cp1252 for old mods compatibility)

If you need to replace font for your mod, just replace fonts.wad and 
gfx.wad. If checksum is different, fonts will not be replaced by fnt 
files (but con_charset will not select different codepages anymore)

If you still need con_charset to work, leave original wads and unpack 
fnt files for each charset

**Comment by Vladislav4KZ** [comment]
@Vad1mCSO2 your character placement in bmp doesn't match their coordinates in creditsfont.txt

**Comment by Vad1mCSO2** [comment]
works fine but have weird position like right anchor
[gfx.zip](https://github.com/user-attachments/files/16758078/gfx.zip)

**Comment by Vad1mCSO2** [comment]
a Top left anchor position will be used in Lunatic Vibes F skins

**Comment by Vad1mCSO2** [comment]
![image](https://github.com/user-attachments/assets/47c2fb38-fb05-4dc3-9e07-e58529acbfa0)
![image](https://github.com/user-attachments/assets/f53043c6-917b-4a00-9fd5-7377a4e641ee)
When I multiplying 2 times it takes result with "O" glitch

**Comment by Vad1mCSO2** [comment]
[BKT Fonts by Vad1m_1719.zip](https://github.com/user-attachments/files/16758523/BKT.Fonts.by.Vad1m_1719.zip)
[I will never lose the my bitmap fonts]
