### ISSUE TITLE
SERIOUS ISSUE

### ISSUE THREAD

**Issue by EhanMMMZET** [FWGS/xash3d-fwgs#1828]
no joke but after attempting to compile xash3d 32bit for 64 bit processor on linux mint ive just removed half of my system somehow including settings, firefox and others and also the wi-fi panel so i need help asap

**Comment by a1batross** [comment]
lmao

Better report that to Linux Mint devs. We don't remove anything from your system, and you only need to install 32-bit dependencies. If doing so annihilates your system, it's a system bug.

**Comment by orangechickenpasta** [comment]
Same issue on Xubuntu, someone should look into this and update the steps on the read me.
But based on the response you received I don't expect any urgency or care with the information the contributors will provide.

**Comment by EhanMMMZET** [comment]
mb it was mint wilma

**Comment by a1batross** [comment]
Well, I will try doing that on VM, but I'm also using Ubuntu and not having any of these problems.

**Comment by a1batross** [comment]
Yep, that's installing libsdl2-dev:i386 that breaks everything.

This is still a system bug, but I think I know the possible workaround.

**Comment by EhanMMMZET** [comment]
oh, unfortunately i moved to opencore legacy patcher cause i installed it on a macbook

**Comment by a1batross** [comment]
After a quick look, it seems the culprit is the apt/apt-get dependency resolver.

If I mark as installed manually one of the packages that apt wants to delete, it doesn't remove anything. Easier way is to install the same package with `aptitude` which doesn't remove anything. I will edit `README.md` accordingly.

As for repairing the system, I'm not sure how to do this, as I don't know what the packages were removed on your system. That's something user should know better.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/commit/f42553d0e1dc9f96ae02d7b9726a6a56dda6aebc
