### ISSUE TITLE
Is it GPL?

### ISSUE THREAD

**Issue by marcikaa78** [FWGS/xash3d-fwgs#1857]

**Comment by a1batross** [comment]
It is because it's derived from Quake, Quake 2 and Dark Places.

However, Xash3D heavily relies on Half-Life SDK headers which by its license aren't GPL compatible, and can be even considered proprietary, despite that API was ruled to be non-copyrightable. Xash3D also loads Half-Life binaries into it's memory, which isn't something GPL allows in a shared memory space.

Also, Uncle Mike in his eternal wisdom copied some parts of leaked Half-Life 2 beta and publicly admitted it. It is easily identifiable, it includes sound mixer, netchan and GL decals. I'm planning to rewrite them at some point and successfully did it for VOX, DSP and minor sound utils, but don't have enough time to continue working on it.

We are a very small team of enthusiasts and unfortunately can't afford a lawyer to work on this. So far nobody is complained.

**Comment by a1batross** [comment]
If you're looking into a complete GPL compliant solution for Half-Life, I recommend you looking into FreeHL/FTEQW. The developers of it are doing great job at providing Half-Life compatible entities set and FTEQW supports all Half-Life assets formats.

**Comment by nekonomicon** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/63
