### ISSUE TITLE
Setting CVar value directly by pointer obtained with pfnCVarGetPointer does nothing

### ISSUE THREAD

**Issue by jarcen** [FWGS/xash3d-fwgs#1912]
For reference, from HLDSK: `#define CVAR_GET_POINTER (*g_engfuncs.pfnCVarGetPointer)`

Doing this when server is active:

```c++
CVAR_GET_POINTER("sv_gravity")->value = 10;
```

does nothing compared to 1.1.1.0. Yes, in both engines this doesn't visually update CVar value when asked from console but in original engine it actually changes gravity on server.

I know there are more legitimate ways to do that but in my knowledge they require setting CVar by it's name which involves passing string as argument and doing lookup. So it's expensive and spams console. For gravity it doesn't matter, it was only the point when I realized something is definitely up. Originally, I investigated why changing `sv_stepsize` on the fly stopped working. And this one is more important. Typical usage pattern that requires frequent change on the fly is: increasing `sv_stepsize`, doing `pfnMoveToOrigin` and then reverting step size. Why:

1. Making big monsters that don't suck when walking(otherwise they get caught on every ant-sized obstacle compared to their size).
2. Automatic navmesh building for bots. Involves making invisible ent that slides around the map to record where bot can go. Setting step size to 63 allows it to automatically climb onto anything that can be climbed by players via duck+jump, like crates.

**Comment by a1batross** [comment]
>So it's expensive and spams console

It isn't that expensive, doing like 800 string comparisons on an alphabetically sorted linked list isn't really expensive even for a CPU made 20 years ago. In Xash it's even faster because we put all cvars, commands and aliases into a hashmap.

**Comment by a1batross** [comment]
There are two reasons why directly changing movevar value (both `sv_gravity` and `sv_stepsize` are so called movevars, they directly affect the physics) doesn't work in Xash compared to GoldSrc.

1) GoldSrc caches the movevar value and compares it to cvar value each frame. We don't do that because we have a much better way to track cvar modifications.

Here I wanted to check ReHLDS source code to directly link you what GoldSrc does and just two hours ago they reworked movevars sync code, so directly changing cvar value through a pointer won't sync it anymore, and I find it absolutely hilarious in the context of this bugreport: https://github.com/rehlds/ReHLDS/commit/df862d9bb6069084ee17b23135152c57b748e40e. Great timing.

2) Not sure about this one, but maybe GoldSrc in its physics code doesn't use the movevar value but instead uses cvar value, so for server-side entities it doesn't require a sync. This is a valid concern for some sort of bug compatibility, but is there any real world usecase for this?

**Comment by a1batross** [comment]
You can add `FCVAR_UNLOGGED` to the cvar flags, that will stop the spam in the console.

**Comment by a1batross** [comment]
Oh, that's correct. I should look into it.

Also, I think we might modify server physics code so it uses cvar values rather than movevar values.

**Comment by a1batross** [comment]
Yeah, I'm closing this.

Entity physics now take the current cvar values rather than synchronized movevars values, and movevars are now only used in player movement code.
