### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Skye450** [FWGS/xash3d-fwgs#1931]
I suddenly got banned, I don't know why record hud![Screenshot_2024-12-24-19-47-13-516_su.xash.engine.test.jpg](https://github.com/user-attachments/assets/3f2e4fc4-1063-4e30-9326-5cc08ecb0080)

**Comment by qq430950189** [comment]
Ban Details:
The ban was issued by the server administrator CSMOV.RU | Zombie Biohazard due to the use of cheats.
The ban lasts for 1 week and 1 day, starting on December 24, 2024, at 21:34:01 and ending on January 1, 2025, at 21:34:01.
The player was flagged for cheating using the IP address 197.146.101.198 and Steam ID STEAM 1:0:1723237113.
it's my first time to know that cs16client have a steamid hhh,maybe your ip was banned because others abuse action on the server.i think it's not a problem about xash3d also cs16client.

**Comment by a1batross** [comment]
I don't care if you really got banned yourself. It's your problems, not an engine bug.

**Comment by Skye450** [comment]
This happens to me a lot in Russian servers. + Client fake

**Comment by Skye450** [comment]
When I enter XP servers I have level 17 and when I exit it is level 0 steamid don't save

**Comment by mittorn** [comment]
Xash3D is literally fake client, so may trigger server's anticheat. It is ok, 
try contact server administration or just do not play on servers with fake 
client detection or some cheat detection mods

**Comment by qq430950189** [comment]
> 当我进入 XP 服务器时，我的级别是 17，而当我退出时，我的级别是 0，steamid 没有保存

em the steamid is a string about generating so you should try some low user identity server.such as simply defuse bomb server.
