### ISSUE TITLE
Please upload binaries to GitHub Releases, not a git repository

### ISSUE THREAD

**Issue by probonopd** [FWGS/xash3d-fwgs#47]
Please upload binaries to GitHub Releases:
https://github.com/FWGS/xash3d-fwgs/releases

**Comment by nekonomicon** [comment]
Why?
It's not stable for releases yet.
You can download fresh test builds from xash3d-deploy repo.

**Comment by a1batross** [comment]
Nope. 

Why? Because GitHub Releases is intended for stable or beta releases. Flooding it with every built version is bad idea. 

So until we can use git repository for it, we will use it. You're not supposed to clone this repository, so just take binaries from directly by raw download.

**Comment by a1batross** [comment]
Yeah, we will add beta release, as soon it will be ready for it. 

For now, the engine isn't finished yet and we're still implememting planned features and moving some code from Old Engine. As you can see in Old Engine repo(`xash3d` repository), we already using GitHub Releases.

**Comment by probonopd** [comment]
> Why?

Storing binaries in git is not good practice:

- https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/
- https://www.quora.com/Should-binary-files-be-stored-in-a-Git-repository

> It's not stable for releases yet.

It doesn't have to be stable in order to be put on GitHub Releases. The name is somewhat misleading. Many projects have a "continuous build" release, e.g.,:

https://github.com/Subsurface-divelog/subsurface/releases/tag/continuous

**Comment by nekonomicon** [comment]
>Storing binaries in git is not good practice:

Who stored binaries in xash3d-fwgs repository?

>You can download fresh test builds from xash3d-deploy repo.

This repo contains only README.md with links on travis builds

**Comment by a1batross** [comment]
@probonopd 

>Storing binaries in git is not good practice:

I recommend you do a research on how we manage deploy repository. :)

Instead of just commiting new things, script is initializing new git repository, commits binaries to it, and force-pushes to `xash3d-deploy` repo. GitHub periodically runs a garbage collect then and cleans up lost objects. A proof is that repository size isn't increased in gigabytes after years of intensive using repository as a "cloud for build artifacts".

Just don't try to clone this and that's all. 

>Many projects have a "continuous build" release

I know. And this is a completely useless, as:
1) Takes space on GitHub servers and eventually they may suggest me "use paid services or GTFO". And I don't plan to move GitHub Premium.
As I said, method with deploy repository doesn't takes so much space, due to the rewriting git history and garbage collection.
2) From user's point of view, trying to find a latest **stable** release will be a pain. As far as I know, latest release doesn't shows first if there is newer prereleses.
Instead of this, deploy repository is something that doesn't shows up for normal users, but these cool guys who are interested in development may easily find this repo.

**Comment by a1batross** [comment]
Yes, I see, we can rewrite the tag. But even this isn't solves problem completely. As new engine will stabilize, master branch will freeze, and a lot of new branches may be created. Yes, I clean them time to time, but in Releases it may create unneeded noise.

**Comment by a1batross** [comment]
Well, I thought about this once more time. 

This maybe should be added. Because it will be easier to deliver binaries for releases. Currently, each port maintainer builds release version by hand and uploads to GitHub Releases(or asks me to upload). It will be really good if it's will be offloaded to Travis.

**Comment by probonopd** [comment]
> Takes space on GitHub servers and eventually they may suggest me "use paid services or GTFO"

Fwiw, I have put continuous builds on GitHub Releases for a __lot__ of projects and never got that suggestion, not once.

**Comment by a1batross** [comment]
Added. Thank you for pointing it!

**Comment by probonopd** [comment]
Thanks, however `x86_64.AppImage` is missing. Most users have 64-bit machines those days. If 32-bit libs are needed, those need to be bundled inside the AppImage as well, as we are doing e.g,. in https://github.com/probonopd/libhookexecv/blob/48fe7ddfe3ab73ab08479eaea51a02f5a669ba37/winedeploy.sh#L29-L49

**Comment by mittorn** [comment]
1. We do not use execve on our binaries so libhookexecv is useless here
2. We do not have dependencies to bundle really. If target system does not support opengl via x11 or wayland and sound via alsa or pulseaudio, we cannot bring it to that system

**Comment by a1batross** [comment]
@probonopd ok, you're so aggressively advertising your "crutch", so I have tried it.

I have:
1. Absolutely clean Xubuntu 19.04 for amd64 installed on VirtualBox. OpenGL is available, version 2.1, which is enough for us.
2. Latest `Wine_Windows_Program_Loader-3.20-x86-64.AppImage` from your link.
3. Latest `xash3d-vc.7z`, which is a Windows build of Xash3D FWGS. Of course, built for i386.

The wine settings application runs fine. But once I tried running a game engine, that requires an OpenGL implementation, your Wine is completely **failed**.
![85i7EmJcUvQ](https://user-images.githubusercontent.com/3213697/60403689-3c99c700-9ba9-11e9-8266-bf3ae88ed818.jpg)

This "No matching GL pixel format available" means that SDL2 can't initialize OpenGL. You know why? You can't just take `libGL.so.1` with you in AppImage. Since it vendor-specific library of OpenGL implementation. It either exists on the host system, either it does not. You can't wrap it, you can't include it, you can't really do anything with it without drastically losing performance.

Releasing an amd64 game engine is useless for us, because **compatibility**. No one needs a compatible game engine, that can't run existing games for it out-of-box.
So the only option we have is to release ONLY i386 builds of Xash3D FWGS. On other platforms like ARM we're not tied with compatibility, since this platform does not have it's own proprietary games at all.

So how can you ask for `x86_64` AppImage knowing that it's not possible? It was discussed for a hundred times since this fork exists. 

Instead of breaking 32-bit support in Linux distributions, I would recommend implementing a proper multilib. Windows does have it for years. Are Linux devs and users so much worse?

**Comment by probonopd** [comment]
Thanks for testing @a1batross. I will admit that I know nothing about how OpenGL and its drivers work. So would the solution be to bundle all the possible OpenGL drivers from all vendors?

**Comment by mittorn** [comment]
No. You cannot bundle proprietary drivers which many people use. And incompatible driver may crash the system. It must be solved in distro, not in package.
There are 2 possible package-side solutions:
1. Bundle software-only gl/vulkan implementations
2. Build some remote driver implementation (like virgl-vtest for example), that will use external process for render. But virgl-vtest does not work with amdgpu-pro for some reason. Maybe because of bad shader compiler that comes from ATI
Indirect rendering will work too, but it not enough for most wine apps

**Comment by probonopd** [comment]
> No. You cannot bundle proprietary drivers which many people use.

For license reasons or for technical reasons?

**Comment by philipzae** [comment]
@a1batross did you try `xash3d-vc.7z` in regular wine or playonlinux? If not could you test it and see if it has any different results than the wine appimage.

**Comment by a1batross** [comment]
@probonopd yep, that's what I said. You have just no choice.

And I don't think that NVIDIA would let you include their proprietary driver into your AppImage. And the technical problem is that I suppose even with opensource libraries something may break. 

Bringing even not related to libGL libraries at first glance, may cause problems with system. Even Valve is struggling with this. Just search "steam undefined symbol" or "steam driver pointer missing" and you will get really too much results about missing symbol in various libraries that Steam is bringing with it's runtime, [example1](https://github.com/ValveSoftware/steam-for-linux/issues/4706), [example2](https://github.com/ValveSoftware/steam-for-linux/issues/3204), [example3](https://github.com/ValveSoftware/steam-for-linux/issues/4451). Solution? Removing the runtime!

@philipzae Installing any of [wine, wine64, playonlinux] packages on Ubuntu installs i386 libraries as well. You will have multilib anyway, so it will run. (for me it shows an interesting graphical artifacts, but it's probably VMSVGA's OpenGL support in upstream mesa)

Installation log: https://gist.github.com/a1batross/e721782c5b15e9dc5c6f6a2bb485d59c

![ZJkvWxT_E5o](https://user-images.githubusercontent.com/3213697/60541562-8b1aa300-9d1a-11e9-949d-5c0401bea413.jpg)

**Comment by a1batross** [comment]
I apologize to anyone who "watches" this repository, I wasn't right about listening to @probonopd friendly advice. 

I've restored repository deployment, because GitHub at this time can't opt-out users from sending emails about prereleases, effectively hitting the mail server limits of some of our contributors. 

Prereleases publishing will be uncommented, until GitHub fixes itself and will not spam with prerelease announcements.
