### ISSUE TITLE
3DS port

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d-fwgs#53]
The original Xash3DS was available for the 3DS, is that planned here?

**Comment by nekonomicon** [comment]
Ask Xash3DS port author.
>The original Xash3DS

What is "original"? Xash3DS based on Xash3d FWGS 0.19.x.

**Comment by a1batross** [comment]
Not planned. I doubt that any of current devs have 3ds already.


When Xash3DS author ports will take an effort to port new engine to 3DS, send a PR and it will be merged, keep it maintained...

I'm really would glad to see PRs with engine ports, because new engine fork is designed to be even more flexible than previous old fork.
