### ISSUE TITLE
Feature Request: Adding a new CVar for Software mode style liquid in OpenGL

### ISSUE THREAD

**Issue by TwelveEyes** [FWGS/xash3d-fwgs#68]
I've always preferred the Software mode style liquid effect to the hardware accelerated D3D/OpenGl texture warping liquid effect. I think it would be nice to have a CVar to toggle the default OpenGL liquid effect with the Software mode one. Something like: "gl_software_liquid" as the toggle, for example.

Example of the Software liquid effect: [https://www.youtube.com/watch?v=DHgtWODyUUo](url)

**Comment by a1batross** [comment]
Hi. 

It's possible, but for now only in our [ref_soft](https://github.com/mittorn/ref_soft) renderer. Meanwhile, with classic OpenGL renderer, which is obviously ref_gl, it's nearly impossible due to fixed pipeline of legacy GL. ref_gl is meant to use legacy GL, to be compatible with vanilla Half-Life rendering.

**Comment by mittorn** [comment]
Are there any implementation of this effect?

**Comment by TwelveEyes** [comment]
Magic Nipples did an implementation pretty close to what you find in Software mode in his Xash3D build for Preliminary. Might wanna get in touch with him about it.

Video of the effect: [https://www.youtube.com/watch?v=Itw_KSefIoI](url)

**Comment by a1batross** [comment]
Not planned, until for now.
